version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --no-include-email --region ap-southeast-2)

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t my-flask-app .
      - docker tag my-flask-app:latest <AWS_ACCOUNT_ID>.dkr.ecr.ap-southeast-2.amazonaws.com/my-flask-app:latest

  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push 927414202399.dkr.ecr.ap-southeast-2.amazonaws.com/my-flask-app:latest
      - echo Build completed successfully!

artifacts:
  files:
    - '**/*'
